interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [ "app",
]

[[modules ]]
path = "crew.agents"
depends_on = ["models", "config"]

[[modules ]]
path = "main"
depends_on = ["routers"]

[[modules ]]
path = "crew.crew"
depends_on = ["config", "crew.tools", "models", "crew.tasks", "crew.agents"]

[[modules ]]
path = "crew.tools"
depends_on = ["config"]

[[modules ]]
path = "utils"
depends_on = []
utility = true

[[modules ]]
path = "models"
depends_on = []

[[modules ]]
path = "config"
depends_on = []

[[modules ]]
path = "crew.tasks"
depends_on = ["models"]

[[modules ]]
path = "routers"
depends_on = ["models", "crew.crew"]
