name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Run clean
        run: make clean

      - name: Run lint
        run: make lint

      - name: Run format
        run: make format
